CADC-11343: remove dependencies on old log4j, internal CADC libraries
opencadc/science-portal-deprecated pull request #22
Opened 2022-06-08 21:40 UTC by hjeeves

…so only uses open-source libraries.

2022-06-08 23:40 UTC, at88mph requested changes

2022-06-08 23:40 UTC, at88mph commented on build.gradle
> +    intTest_default_web_app_url = 'https://www-rc.canfar.net'
It's `https://rc-www.canfar.net`.

2022-06-09 15:14 UTC, hjeeves commented on build.gradle
> +    intTest_default_web_app_url = 'https://www-rc.canfar.net'
whoops. thanks.

2022-06-09 15:15 UTC, at88mph approved these changes

2022-06-09 15:16 UTC, merged