CAC-11604: Platform Usage panel for Science Portal
opencadc/science-portal-deprecated pull request #39
Opened 2023-02-06 19:18 UTC by hjeeves

Changes:
- progress bars have more granularity (one per panel, as 2 panels can now be refreshed separately.)
- page state can be grabbed from the react app in order to set progress bars
- science_portal_session.js javascript contains calls to get platform usage (skaha/session?view=stats)
- new SciencePortalPlatformUsage react component to display values
- changes in App.js for the extra panel

Technical debt changes:
- indentation in App.js was severely off in some areas
- remove commented code in App.js, science_portal_core.js, science_portal.js

Tested manually on a canfar vm

2023-02-07 22:00 UTC, at88mph requested changes

2023-02-07 22:00 UTC, at88mph commented on TECH_README.md
> +.env file needs to be set up in the root of your local copy of the code, with contents similar to
It actually just needs to be in the same place as the `docker-compose.yml` file.

Or more appropriately:

> Relative path MUST be resolved from the Compose file’s parent folder.

2023-02-07 22:00 UTC, at88mph commented on public/dev/js/science_portal.js
> +      portalCore.setPageState("all", "primary", true, '')
Mix of quotes here.

2023-02-07 22:00 UTC, at88mph commented on public/dev/js/science_portal.js
> +        var currentState = _reactApp.updateSessionList(sessDataObj)
This variable isn't used anywhere.

2023-02-07 22:00 UTC, at88mph commented on public/dev/js/science_portal_core.js
> +    // function setPageState(barType, isAnimated, formMsg, sessionActionAlertMsg) {
This can be removed.

2023-02-07 22:00 UTC, at88mph commented on public/dev/js/science_portal_core.js
> +          // pageState[pageSection].alert = _mkAlertData(barType, )
This can be removed.

2023-02-07 22:00 UTC, at88mph commented on public/dev/js/science_portal_core.js
> +          // var show = true
This can be removed.

2023-02-07 22:00 UTC, at88mph commented on public/dev/js/science_portal_session.js
> +            // var chartHeight = ((biggestCount + 10) % 10 ) * 10
This can be removed.

2023-02-07 22:00 UTC, at88mph commented on public/dev/js/science_portal_session.js
> +    // function getSessionListAjax(serviceURL, sessionData) {
This can be removed.

2023-02-07 22:00 UTC, at88mph commented on public/dev/js/science_portal_session.js
> +          // getSessionListAjax(_selfPortalSess.sessionServiceURL)
This can be removed.

2023-02-07 23:54 UTC, hjeeves commented on public/dev/js/science_portal_session.js
> +          // getSessionListAjax(_selfPortalSess.sessionServiceURL)
good catch. this code got merged into a different more generalized function and I didn't remove the original one!

2023-02-07 23:54 UTC, hjeeves commented on public/dev/js/science_portal_session.js
> +    // function getSessionListAjax(serviceURL, sessionData) {
(as the comment below)

2023-02-07 23:57 UTC, hjeeves commented on public/dev/js/science_portal_core.js
> +    // function setPageState(barType, isAnimated, formMsg, sessionActionAlertMsg) {
removed the commented function statement & updated the comment.

2023-02-07 23:57 UTC, hjeeves commented on public/dev/js/science_portal_core.js
> +          // pageState[pageSection].alert = _mkAlertData(barType, )
ok

2023-02-07 23:57 UTC, hjeeves commented on public/dev/js/science_portal_core.js
> +          // var show = true
ok

2023-02-07 23:57 UTC, hjeeves commented on public/dev/js/science_portal_session.js
> +            // var chartHeight = ((biggestCount + 10) % 10 ) * 10
ok

2023-02-07 23:58 UTC, hjeeves commented on public/dev/js/science_portal.js
> +      portalCore.setPageState("all", "primary", true, '')
Somehow, always has to be one left!

2023-02-07 23:58 UTC, hjeeves commented on public/dev/js/science_portal.js
> +        var currentState = _reactApp.updateSessionList(sessDataObj)
removed.

2023-02-08 01:12 UTC, hjeeves commented on TECH_README.md
> +.env file needs to be set up in the root of your local copy of the code, with contents similar to
I dug a bit further into what is using this .env file. It's npm, and it's only used to start up the local version. (command in package.json 'sudo react-scripts start', which uses npm under the covers.  The simplest way is to have this .env file at the application root so npm can find it. I added a link to documentation so if anyone wants to have a different configuration (or have different env files for different setups,) it's possible.

2023-02-08 01:14 UTC, at88mph approved these changes

2023-02-08 18:06 UTC, merged